export const ERROR_CODES = {
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  SESSION_CONSUMED: "SESSION_CONSUMED",
  INVALID_TOKEN: "INVALID_TOKEN",
  ORIGIN_MISMATCH: "ORIGIN_MISMATCH",
  INVALID_STATE_TRANSITION: "INVALID_STATE_TRANSITION",
  PROVIDER_ERROR: "PROVIDER_ERROR",
  RATE_LIMITED: "RATE_LIMITED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface ApiErrorBody {
  error: {
    code: ErrorCode;
    message: string;
  };
}

/** Default HTTP status to map each error code to. The API is free to override per-case. */
export const ERROR_CODE_HTTP_STATUS: Readonly<Record<ErrorCode, number>> = {
  SESSION_NOT_FOUND: 404,
  SESSION_EXPIRED: 410,
  SESSION_CONSUMED: 410,
  INVALID_TOKEN: 401,
  ORIGIN_MISMATCH: 403,
  INVALID_STATE_TRANSITION: 409,
  PROVIDER_ERROR: 502,
  RATE_LIMITED: 429,
  VALIDATION_ERROR: 400,
  INTERNAL_ERROR: 500,
};
